// <auto-generated />
using System;
using AppWeb.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppWeb.Server.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20221122141649_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AppWeb.Shared.Models.ActionItem", b =>
                {
                    b.Property<int>("ActionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActionId"), 1L, 1);

                    b.Property<DateTime?>("CloseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DescriptionA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeveloperId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OpenDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlanDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tilte")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActionId");

                    b.HasIndex("DeveloperId");

                    b.ToTable("ActionItems");
                });

            modelBuilder.Entity("AppWeb.Shared.Models.Developer", b =>
                {
                    b.Property<int>("DeveloperId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeveloperId"), 1L, 1);

                    b.Property<string>("AmdtC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AmdtP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Analyse")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Atelier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlSAQ")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlocM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BlocT")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CloseOn")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CodePrio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CommentairePrio")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Commentaires")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("DImi")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTbee")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTbem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DTrd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCrea")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinBE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinBEE")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinDT")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinMI")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateFinSQ")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateP")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSolde")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSoldePr")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateSuivi")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DesignationC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ECO")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ECOCount")
                        .HasColumnType("int");

                    b.Property<bool>("ECOSelected")
                        .HasColumnType("bit");

                    b.Property<int>("ECOYear")
                        .HasColumnType("int");

                    b.Property<string>("ECR")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FEE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndiceC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IndiceP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PNP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Produit")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RAF")
                        .HasColumnType("int");

                    b.Property<string>("Statut")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DeveloperId");

                    b.ToTable("Developers");
                });

            modelBuilder.Entity("AppWeb.Shared.Models.ActionItem", b =>
                {
                    b.HasOne("AppWeb.Shared.Models.Developer", "Developer")
                        .WithMany("ActionItems")
                        .HasForeignKey("DeveloperId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Developer");
                });

            modelBuilder.Entity("AppWeb.Shared.Models.Developer", b =>
                {
                    b.Navigation("ActionItems");
                });
#pragma warning restore 612, 618
        }
    }
}
